### PR TITLE
New: Completed unittest for model

### PR DESCRIPTION
**Pull request by MikeS96**

### CODE REVIEW

**Comment by MikeS96** [comment]
Bro... I think this is one of the last commits to this code and it makes me sad :(

**Comment by zestian56** [comment]
I dont want to leave mr Bro...

**Review by zestian56 — APPROVED** [review]

**Comment by MikeS96** [comment]
Mr. Stark... I do not wanna go...

**Comment by gsg213** [comment]
https://user-images.githubusercontent.com/29763076/114197572-1c6b7000-9918-11eb-8cdb-c1e09d4b11ed.mp4

**Pull request merged**
